//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace store
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class storeEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new storeEntities object using the connection string found in the 'storeEntities' section of the application configuration file.
        /// </summary>
        public storeEntities() : base("name=storeEntities", "storeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new storeEntities object.
        /// </summary>
        public storeEntities(string connectionString) : base(connectionString, "storeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new storeEntities object.
        /// </summary>
        public storeEntities(EntityConnection connection) : base(connection, "storeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<category> categories
        {
            get
            {
                if ((_categories == null))
                {
                    _categories = base.CreateObjectSet<category>("categories");
                }
                return _categories;
            }
        }
        private ObjectSet<category> _categories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<product> products
        {
            get
            {
                if ((_products == null))
                {
                    _products = base.CreateObjectSet<product>("products");
                }
                return _products;
            }
        }
        private ObjectSet<product> _products;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<user> users
        {
            get
            {
                if ((_users == null))
                {
                    _users = base.CreateObjectSet<user>("users");
                }
                return _users;
            }
        }
        private ObjectSet<user> _users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<order> orders
        {
            get
            {
                if ((_orders == null))
                {
                    _orders = base.CreateObjectSet<order>("orders");
                }
                return _orders;
            }
        }
        private ObjectSet<order> _orders;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Login> Logins
        {
            get
            {
                if ((_Logins == null))
                {
                    _Logins = base.CreateObjectSet<Login>("Logins");
                }
                return _Logins;
            }
        }
        private ObjectSet<Login> _Logins;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the categories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocategories(category category)
        {
            base.AddObject("categories", category);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the products EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToproducts(product product)
        {
            base.AddObject("products", product);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTousers(user user)
        {
            base.AddObject("users", user);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the orders EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToorders(order order)
        {
            base.AddObject("orders", order);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Logins EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLogins(Login login)
        {
            base.AddObject("Logins", login);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="storeModel", Name="category")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class category : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new category object.
        /// </summary>
        /// <param name="id_cat">Initial value of the id_cat property.</param>
        public static category Createcategory(global::System.Int32 id_cat)
        {
            category category = new category();
            category.id_cat = id_cat;
            return category;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_cat
        {
            get
            {
                return _id_cat;
            }
            set
            {
                if (_id_cat != value)
                {
                    Onid_catChanging(value);
                    ReportPropertyChanging("id_cat");
                    _id_cat = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_cat");
                    Onid_catChanged();
                }
            }
        }
        private global::System.Int32 _id_cat;
        partial void Onid_catChanging(global::System.Int32 value);
        partial void Onid_catChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String decription
        {
            get
            {
                return _decription;
            }
            set
            {
                OndecriptionChanging(value);
                ReportPropertyChanging("decription");
                _decription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("decription");
                OndecriptionChanged();
            }
        }
        private global::System.String _decription;
        partial void OndecriptionChanging(global::System.String value);
        partial void OndecriptionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="storeModel", Name="Login")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Login : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Login object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static Login CreateLogin(global::System.Int32 id)
        {
            Login login = new Login();
            login.id = id;
            return login;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String username
        {
            get
            {
                return _username;
            }
            set
            {
                OnusernameChanging(value);
                ReportPropertyChanging("username");
                _username = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("username");
                OnusernameChanged();
            }
        }
        private global::System.String _username;
        partial void OnusernameChanging(global::System.String value);
        partial void OnusernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> time
        {
            get
            {
                return _time;
            }
            set
            {
                OntimeChanging(value);
                ReportPropertyChanging("time");
                _time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("time");
                OntimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _time;
        partial void OntimeChanging(Nullable<global::System.DateTime> value);
        partial void OntimeChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="storeModel", Name="order")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class order : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new order object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static order Createorder(global::System.Int32 id)
        {
            order order = new order();
            order.ID = id;
            return order;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cust_name
        {
            get
            {
                return _cust_name;
            }
            set
            {
                Oncust_nameChanging(value);
                ReportPropertyChanging("cust_name");
                _cust_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("cust_name");
                Oncust_nameChanged();
            }
        }
        private global::System.String _cust_name;
        partial void Oncust_nameChanging(global::System.String value);
        partial void Oncust_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cust_adress
        {
            get
            {
                return _cust_adress;
            }
            set
            {
                Oncust_adressChanging(value);
                ReportPropertyChanging("cust_adress");
                _cust_adress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("cust_adress");
                Oncust_adressChanged();
            }
        }
        private global::System.String _cust_adress;
        partial void Oncust_adressChanging(global::System.String value);
        partial void Oncust_adressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String mob1
        {
            get
            {
                return _mob1;
            }
            set
            {
                Onmob1Changing(value);
                ReportPropertyChanging("mob1");
                _mob1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("mob1");
                Onmob1Changed();
            }
        }
        private global::System.String _mob1;
        partial void Onmob1Changing(global::System.String value);
        partial void Onmob1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String mob2
        {
            get
            {
                return _mob2;
            }
            set
            {
                Onmob2Changing(value);
                ReportPropertyChanging("mob2");
                _mob2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("mob2");
                Onmob2Changed();
            }
        }
        private global::System.String _mob2;
        partial void Onmob2Changing(global::System.String value);
        partial void Onmob2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String product_name
        {
            get
            {
                return _product_name;
            }
            set
            {
                Onproduct_nameChanging(value);
                ReportPropertyChanging("product_name");
                _product_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("product_name");
                Onproduct_nameChanged();
            }
        }
        private global::System.String _product_name;
        partial void Onproduct_nameChanging(global::System.String value);
        partial void Onproduct_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String size
        {
            get
            {
                return _size;
            }
            set
            {
                OnsizeChanging(value);
                ReportPropertyChanging("size");
                _size = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("size");
                OnsizeChanged();
            }
        }
        private global::System.String _size;
        partial void OnsizeChanging(global::System.String value);
        partial void OnsizeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String trans
        {
            get
            {
                return _trans;
            }
            set
            {
                OntransChanging(value);
                ReportPropertyChanging("trans");
                _trans = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("trans");
                OntransChanged();
            }
        }
        private global::System.String _trans;
        partial void OntransChanging(global::System.String value);
        partial void OntransChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String notes
        {
            get
            {
                return _notes;
            }
            set
            {
                OnnotesChanging(value);
                ReportPropertyChanging("notes");
                _notes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("notes");
                OnnotesChanged();
            }
        }
        private global::System.String _notes;
        partial void OnnotesChanging(global::System.String value);
        partial void OnnotesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> total
        {
            get
            {
                return _total;
            }
            set
            {
                OntotalChanging(value);
                ReportPropertyChanging("total");
                _total = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("total");
                OntotalChanged();
            }
        }
        private Nullable<global::System.Int32> _total;
        partial void OntotalChanging(Nullable<global::System.Int32> value);
        partial void OntotalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> orderdate
        {
            get
            {
                return _orderdate;
            }
            set
            {
                OnorderdateChanging(value);
                ReportPropertyChanging("orderdate");
                _orderdate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("orderdate");
                OnorderdateChanged();
            }
        }
        private Nullable<global::System.DateTime> _orderdate;
        partial void OnorderdateChanging(Nullable<global::System.DateTime> value);
        partial void OnorderdateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String comfirm
        {
            get
            {
                return _comfirm;
            }
            set
            {
                OncomfirmChanging(value);
                ReportPropertyChanging("comfirm");
                _comfirm = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("comfirm");
                OncomfirmChanged();
            }
        }
        private global::System.String _comfirm;
        partial void OncomfirmChanging(global::System.String value);
        partial void OncomfirmChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String agent_name
        {
            get
            {
                return _agent_name;
            }
            set
            {
                Onagent_nameChanging(value);
                ReportPropertyChanging("agent_name");
                _agent_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("agent_name");
                Onagent_nameChanged();
            }
        }
        private global::System.String _agent_name;
        partial void Onagent_nameChanging(global::System.String value);
        partial void Onagent_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ftotal
        {
            get
            {
                return _ftotal;
            }
            set
            {
                OnftotalChanging(value);
                ReportPropertyChanging("ftotal");
                _ftotal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ftotal");
                OnftotalChanged();
            }
        }
        private Nullable<global::System.Int32> _ftotal;
        partial void OnftotalChanging(Nullable<global::System.Int32> value);
        partial void OnftotalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> transcost
        {
            get
            {
                return _transcost;
            }
            set
            {
                OntranscostChanging(value);
                ReportPropertyChanging("transcost");
                _transcost = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("transcost");
                OntranscostChanged();
            }
        }
        private Nullable<global::System.Int32> _transcost;
        partial void OntranscostChanging(Nullable<global::System.Int32> value);
        partial void OntranscostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String note2
        {
            get
            {
                return _note2;
            }
            set
            {
                Onnote2Changing(value);
                ReportPropertyChanging("note2");
                _note2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("note2");
                Onnote2Changed();
            }
        }
        private global::System.String _note2;
        partial void Onnote2Changing(global::System.String value);
        partial void Onnote2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> com_date
        {
            get
            {
                return _com_date;
            }
            set
            {
                Oncom_dateChanging(value);
                ReportPropertyChanging("com_date");
                _com_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("com_date");
                Oncom_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _com_date;
        partial void Oncom_dateChanging(Nullable<global::System.DateTime> value);
        partial void Oncom_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> count
        {
            get
            {
                return _count;
            }
            set
            {
                OncountChanging(value);
                ReportPropertyChanging("count");
                _count = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("count");
                OncountChanged();
            }
        }
        private Nullable<global::System.Int32> _count;
        partial void OncountChanging(Nullable<global::System.Int32> value);
        partial void OncountChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="storeModel", Name="product")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class product : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new product object.
        /// </summary>
        /// <param name="id_product">Initial value of the id_product property.</param>
        public static product Createproduct(global::System.Int32 id_product)
        {
            product product = new product();
            product.id_product = id_product;
            return product;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_product
        {
            get
            {
                return _id_product;
            }
            set
            {
                if (_id_product != value)
                {
                    Onid_productChanging(value);
                    ReportPropertyChanging("id_product");
                    _id_product = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_product");
                    Onid_productChanged();
                }
            }
        }
        private global::System.Int32 _id_product;
        partial void Onid_productChanging(global::System.Int32 value);
        partial void Onid_productChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> qut
        {
            get
            {
                return _qut;
            }
            set
            {
                OnqutChanging(value);
                ReportPropertyChanging("qut");
                _qut = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("qut");
                OnqutChanged();
            }
        }
        private Nullable<global::System.Int32> _qut;
        partial void OnqutChanging(Nullable<global::System.Int32> value);
        partial void OnqutChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> price
        {
            get
            {
                return _price;
            }
            set
            {
                OnpriceChanging(value);
                ReportPropertyChanging("price");
                _price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("price");
                OnpriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _price;
        partial void OnpriceChanging(Nullable<global::System.Decimal> value);
        partial void OnpriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> id_cat
        {
            get
            {
                return _id_cat;
            }
            set
            {
                Onid_catChanging(value);
                ReportPropertyChanging("id_cat");
                _id_cat = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_cat");
                Onid_catChanged();
            }
        }
        private Nullable<global::System.Int32> _id_cat;
        partial void Onid_catChanging(Nullable<global::System.Int32> value);
        partial void Onid_catChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="storeModel", Name="user")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class user : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new user object.
        /// </summary>
        /// <param name="userid">Initial value of the userid property.</param>
        public static user Createuser(global::System.Int32 userid)
        {
            user user = new user();
            user.userid = userid;
            return user;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 userid
        {
            get
            {
                return _userid;
            }
            set
            {
                if (_userid != value)
                {
                    OnuseridChanging(value);
                    ReportPropertyChanging("userid");
                    _userid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("userid");
                    OnuseridChanged();
                }
            }
        }
        private global::System.Int32 _userid;
        partial void OnuseridChanging(global::System.Int32 value);
        partial void OnuseridChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String username
        {
            get
            {
                return _username;
            }
            set
            {
                OnusernameChanging(value);
                ReportPropertyChanging("username");
                _username = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("username");
                OnusernameChanged();
            }
        }
        private global::System.String _username;
        partial void OnusernameChanging(global::System.String value);
        partial void OnusernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String npassword
        {
            get
            {
                return _npassword;
            }
            set
            {
                OnnpasswordChanging(value);
                ReportPropertyChanging("npassword");
                _npassword = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("npassword");
                OnnpasswordChanged();
            }
        }
        private global::System.String _npassword;
        partial void OnnpasswordChanging(global::System.String value);
        partial void OnnpasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String phone
        {
            get
            {
                return _phone;
            }
            set
            {
                OnphoneChanging(value);
                ReportPropertyChanging("phone");
                _phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("phone");
                OnphoneChanged();
            }
        }
        private global::System.String _phone;
        partial void OnphoneChanging(global::System.String value);
        partial void OnphoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String kind
        {
            get
            {
                return _kind;
            }
            set
            {
                OnkindChanging(value);
                ReportPropertyChanging("kind");
                _kind = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("kind");
                OnkindChanged();
            }
        }
        private global::System.String _kind;
        partial void OnkindChanging(global::System.String value);
        partial void OnkindChanged();

        #endregion

    
    }

    #endregion

    
}
